### ISSUE TITLE
Открытые пулл-реквесты

### ISSUE THREAD

**Issue by HetNeSS** [SBT-community/Starbound_RU#49]
Есть одна тема. Пулл реквесты могут конфликтовать между собой, несколько человек могут переводить один и тот же кусок текста. Есть предложение вывести список файлов, не утвержденных и требующих перевода. Либо своевременно мерджить пуллы чтобы у людей всегда был подходящий материал для работы.

**Comment by Xorras** [comment]
Список выводить с нашей стороны бесмысленно, потому что на .io и так видно эти файлы. А пуллы мерджим по степени их отклика (создателей)
