### ISSUE TITLE
Ошибки и пара вопросов по переводу

### ISSUE THREAD

**Issue by Gerald42** [SBT-community/Starbound_RU#50]
1. В предложении "Нажмите кнопку A или **D , ч**тобы..." лишний пробел перед запятой.
![starbound_2017_07_23_06_02_26_047](https://user-images.githubusercontent.com/30422730/28550676-fb790df0-70e2-11e7-9c7d-9a447c6086ed.png)
---
2. В предложении "Запомните, вы можете открыть двер**ь ,н**аведя..." стоит пробел перед запятой, а не после.
![starbound_2017_07_23_06_02_31_696](https://user-images.githubusercontent.com/30422730/28550732-64536d02-70e3-11e7-885a-ddc8d090a504.png)
---
3. В предложении "Нажмите F, чтобы **использоватьТехнологию**..." пропущен пробел между словами.
![starbound_2017_07_24_01_16_23_818](https://user-images.githubusercontent.com/30422730/28550858-6ba93f4a-70e4-11e7-8ead-a5dd1de1847d.png)
---
И парочка моментов, которые не то, чтобы ошибки, но хотелось бы узнать на счет этого:
Во-первых, почему данный товарищ в форпосте обращается к нам "ты еще не готов(а)"? Исходя из всех текстов в игре, я заметил, что везде фигурирует мужской род. Поэтому такая концовка как минимум слегка удивила. В принципе, дабы не заморачиваться с полом персонажа, можно было бы использовать вариант "вы еще не готовы"; или же создать скрипт, который определял бы пол персонажа и в зависимости от оного прописывал нужный вариант.
![starbound_2017_07_24_02_00_55_925](https://user-images.githubusercontent.com/30422730/28550960-006a939a-70e5-11e7-8777-56c56f54132b.png)
И во-вторых, в разговорах грибов присутствуют апострофы в словах. Это так и должно быть?) Если да, то как нужно это интерпретировать? Словно мягкий звук или?
![starbound_2017_07_23_07_36_49_774](https://user-images.githubusercontent.com/30422730/28550801-024a3f7c-70e4-11e7-8a9d-53d32f0e382a.png)

**Comment by BigWhitePanda** [comment]
Ошибки пофиксил.

**Comment by Xorras** [comment]
Если панда изменил все ошибки, то я вернул мужской пол.

>И во-вторых, в разговорах грибов присутствуют апострофы в словах. Это так и должно быть?) Если да, то как нужно это интерпретировать? Словно мягкий звук или?

Честно? Хз. По английски фраза со скрина выглядит так:
>Halhoom smooth! Chop deka halberdeen cartography!

А еще это остаток странных переводов с нашего бывшего убежища. Чем руководствовался тот человек нам неизвестно. У меня лично фантазии нет для изменения этого, если есть идеи отпишись :D

**Comment by Gerald42** [comment]
> А еще это остаток странных переводов с нашего бывшего убежища. Чем руководствовался тот человек нам неизвестно. У меня лично фантазии нет для изменения этого, если есть идеи отпишись :D

Решил я погуглить на тему этих грибов, и как оказалось, это раса "Агаране" и у них свой весьма неразборчивый язык) На официальном форуме старбаунда есть целые топики посвященные расшифровыванию того, что пытаются сказать эти грибы) В частности вот: 
http://community.playstarbound.com/threads/someone-feel-like-helping-me-with-the-translation-of-the-aragan-language.68824/
Там же наткнулся на попытку разжевывания сугубо этой фразы:
"- Halhoom smooth! Chop deka halberdeen cartography! (Most likely refering to the space travel Humans have done, and their cartography ability. The deka implies decoration; this may mean that they're refering to the spaceship the human came from.)"
Т.е. как видим, четкой интерпретации языка Агаранов не сущесвтует и даже если переводить это на русский, это было бы нечто далеко искаженным от русского языка)
Там же есть небольшой предположительный словарик по мнению пользователей:
Hoom = Hello
Foom = Goodbye
Hal- = implies enthusiasm or joyfulness, or just enhanced emotion.
Clink = money/bartering
Smashroom = weapon/sword
Clinker = One who deals in money = Trader
Clinker House = Trader's house = Store
Hab = Hurt?
Nab = No
Feara = Fear
Plesta = Pleased to
Mesti = Meet/Me
Halb = Help
Cantara = Meet you
Carpa = Make
Fry = Like
Weepa = Welcome
Bizarra = Bizarre
Deka = Decor, decoration
Halberdeen = Ship
Habba = Have
Bravada = Brave, not related to any magic words
Hairthing: Apex
Kissface: Floran
Meat/Hoom Meat: Human
Sillypeck/Cloudchaser: Avian
Clankbeast: Glitch
Squishfish: Hylotl

**Comment by Xorras** [comment]
Хм, интересный пост, посмотрим как это можно применить. Если хочешь, попробуй сам, если есть желание.)
Ссылку на файл оставляю:
https://sbt-community.github.io/?open=translations/texts/dialog/shroom.config.json

**Comment by Gerald42** [comment]
> Если хочешь, попробуй сам, если есть желание.)

Это разве что со временем попробую помочь с этим, так как в системе гитхаба и как тут все устроено еще не разбирался, а наделать чего-то лишнего не хочется)

**Comment by Xorras** [comment]
http://steamcommunity.com/workshop/filedetails/discussion/731751231/133257324797830429/
Тут ссылка с инструкцией.

**Comment by Xorras** [comment]
Этот пост я закрою, если захочешь грибами заняться, создашь отдельно тему)
