### ISSUE TITLE
Ошибки и замечания по переводу [2]

### ISSUE THREAD

**Issue by Gerald42** [SBT-community/Starbound_RU#51]
1. В предложении "Можно стать час**ть** вашего корабля?" должно бы быть "частью" :)
![o2x4qly](https://user-images.githubusercontent.com/30422730/28743351-1ed3beae-7448-11e7-9d44-0cb60450cf68.png)
2. В предложении "Интересно, должно быть, так они показывают, насколько ценят эту вещь." с пунктуацией явно что-то не то. Логичнее было бы поставить точку или многоточие после "интересно", а дальше уже с нового предложения с запятыми.
![rh1pqoz](https://user-images.githubusercontent.com/30422730/28743367-89bbd418-7448-11e7-9bfe-64958d455bb3.png)
3. Тут вопрос в самом построении предложения. Т.к. первые два раза к ГГ обращаются на "Вы", а в последнем идет уже "нанимаешь меня?", что = обращению на ты. Т.е. надо бы везде переделать либо на "Вы", либо на "ты". 
![qv3sxcw](https://user-images.githubusercontent.com/30422730/28743389-0080065a-7449-11e7-9818-2202df80af1a.png)
4. Пропущен пробел в "..корабль класса Оре**л!Н**авестите пингвина Пита..."
![v9yo5ge](https://user-images.githubusercontent.com/30422730/28743433-00be7eca-744a-11e7-9612-a58978b04591.png)
5. В предложении "Могу я присоедини**тся** к покорению звезд?" пропущен "ь" в слове "присоединиться".
![ezupmj8](https://user-images.githubusercontent.com/30422730/28743446-39e75546-744a-11e7-8720-9d6dcae1849d.png)
6. Что это за "органической жизни из тысячелетий назад?" ;D Никогда так в русском языке не говорится) Поставьте тогда уж просто "тысячелетия назад". И еще вместо "свидетельствуют о органической жизни" я бы поставил "об органический жизни", дабы не было две гласных "о" подряд.
![2izczpt](https://user-images.githubusercontent.com/30422730/28743451-5fce9bc0-744a-11e7-9f9b-c78d17613e56.png)
7. В первом предложении лишний мягкий знак "Артефакт Флоран храни**ться** в...".
![s68vk8i](https://user-images.githubusercontent.com/30422730/28743469-0194d564-744b-11e7-9eeb-d1ecf9e40562.png)
8. Я так понимаю, здесь подразумевается "руины были **вскрыты** Флоранами", а не "**скрыты** Флоранами" :)
![qpiamj0](https://user-images.githubusercontent.com/30422730/28743491-93b653b4-744b-11e7-930f-98fc49052570.png)
9. В очередной раз правило "-тся или -ться". На этот раз пропущен "ь" в предложении "Мне нравится охоти**тся**, но..."
![kk2rb0f](https://user-images.githubusercontent.com/30422730/28743501-b7e0b16c-744b-11e7-8860-026abcf1d74a.png)
10. Здесь сразу несколько в одном предложении. Пропущен пробел + лишние символы: "..вызвал меня **наар**ену гладиатор**ов"t**, но я думаю, ты..."
![ar0eipb](https://user-images.githubusercontent.com/30422730/28743521-1ab9583e-744c-11e7-9764-b36142d16518.png)
11. Учитывая, что во всех "пузырьках" и диалогах в конце стоят точки или другие соответствующие знаки препинания, то здесь всего навсего пропущена точка.
![vrxfddq](https://user-images.githubusercontent.com/30422730/28743541-8e736d50-744c-11e7-9d66-5f360c4aa294.png)
12. В диалоге с NPC ученым, который говорит "Дорогой мо**й, в**ыживший! Не знаком ли ты с учеными, которые могли бы **мне** помочь с **моими** исследованиями.". То, что бросается в глаза - выделил жирным. Т.е. непонятно, зачем в первом предложении запятая + я бы исправил тавтологию во втором. К примеру поставить "могли бы помочь мне с исследованиями" или "могли бы помочь с моими исследованиями". Но никак не "мне" + "моими". 
![uhzxduf](https://user-images.githubusercontent.com/30422730/28743552-ac1eefdc-744c-11e7-8d72-47aaf6064148.png)
13. Здесь траблы сугубо с графической составляющей. Текст с заданием наезжает на окошко с наградой. Правда, далеко не уверен, связано ли это с самим переводом или же из-за разницы русской и инглиш версий, где количество текста возможно привязано к определенному спейсу.  
![baqypbp](https://user-images.githubusercontent.com/30422730/28743403-46bfcce0-7449-11e7-98b7-a544da8c24bb.png)
14. Там где "..на востоке от нас and ликвидируй его?", как видим стоит англоязычный союз "and". Помимо этого, если исправлять на русский и писать "и", то надо сразу поправить фразу "ликвидируй его" на "ликвидировать его". 
![zohilk5](https://user-images.githubusercontent.com/30422730/28743420-b80061bc-7449-11e7-8ec2-563867e38010.png)

**Comment by Xorras** [comment]
Просто скажу огромное спасибо за такие отчеты.)

А теперь детально:
>3. Т.е. надо бы везде переделать либо на "Вы", либо на "ты".

Подкорректировал. К слову, они говорят из вежливости в некоторых местах (наверное?). Считай частью характера персонажей. Кто-то вежливый, а кто-то нет.))

>8. Я так понимаю, здесь подразумевается "руины были вскрыты Флоранами", а не "скрыты Флоранами"

Нет, они именно скрыты. Флораны типа прячут их от чужаков.

>13. где количество текста возможно привязано к определенному спейсу.

К сожалению в окнах квестов именно так. Если диалоги (в пузырях) расширяются, то тут всё ограничено... А вообще это может быть от разрешения экрана. (но это не точно (скорее всего нет))

>14. 

Ну "и" исправил, а остальное... такой уж рандомайзер. Посмотрим как подправить построение предложений.

P.S. Не заметил этот пост до релиза. Упс. В следующем тогда будут исправления по этому отчету

**Comment by Gerald42** [comment]
> Просто скажу огромное спасибо за такие отчеты.)

И вам всем тоже большое спасибо за столь объемный проделанный труд) А так, просто хочется, дабы одна из любимых игр радовала глаз на родном языке, и дабы было это все на достойном уровне (на данный момент это ИМХО лучший перевод среди всех имеющихся аналогов). Впервые играл в старбаунд еще в 2013. Тогда же был полный и весьма качественный перевод (даже включая текстуры). Но с тех пор появились все эти ночные сборки и более менее частые обновления, а нормальных переводов уже не существовало. Потому релизную версию 1.0 около 100 часов отбегал в оригинале. Благо знание языка позволяет чувствовать себя более чем комфортно, чтобы проникнуться атмосферой и не упустить столь частую игру слов. Но опять же, куда приятнее лицезреть все на родном языке, т.к. не нужно никак заморачиваться, если вдруг повстречал незнакомое слово или не понял какой-то сленговый оборот)
> Нет, они именно скрыты. Флораны типа прячут их от чужаков.

Я бы и не обратил внимания, если бы не внутриигровой кодекс. В одной из записок, найденных в этих церемониальных пещерах, повествование ведется от лица предыдущих обывателей, где кратко говорится о том, что это был их город, а потом прилетели "существа со звезд" (флоране) и разграбили все, что было (что и натолкнуло на мысль, что флоране вскрыли уже выстроенный город).
Все же интереса ради решил найти, как эта фраза звучит в оригинале и слегка удивился)
Собственно, скрин:
![iurzlib](https://user-images.githubusercontent.com/30422730/28746017-75338554-7484-11e7-9331-aa42da97dd9f.png)
Т.е. конкретно в этом предложении, где переведено "руины скрыты Флоранами", в оригинале подразумевается то, что это место является священным для Флоранов (что вполне логично, учитывая что пещеры-то "церемониальные"). То бишь далеко не то, что они их скрыли или вскрыли. =)
Поэтому возникает вопрос, как вообще в переводе оказалось "скрыты". Разве что сам текст в инглиш версии менялся с течением времени, что вряд ли.

**Comment by Xorras** [comment]
>Поэтому возникает вопрос, как вообще в переводе оказалось "скрыты". разве что сам текст в инглиш версии менялся с течением времени, что вряд ли.

Ну как я уже говорил, у нас раньше странные люди переводили. Где-то да остались их следы. Всё отследить просто нереально)

**Comment by Gerald42** [comment]
> Ну как я уже говорил

Блин, я только сейчас увидел, что человек ответивший в предыдущем и в этом топике один и тот же, т.е. ты) Теперь-то все встало на свои места)

**Comment by Gerald42** [comment]
> Ну как я уже говорил

Блин, я только сейчас понял/увидел, что человек ответивший мне как в том, так и в этом топике один и тот же т.е. ты) 
Теперь-то все встало на свои места)

**Comment by Xorras** [comment]
Закрою пока. Найдешь еще, создавай еще одну тему.)
