### ISSUE TITLE
Баги игры или рус-а?

### ISSUE THREAD

**Issue by MonsterNya** [SBT-community/Starbound_RU#55]
1. Почему-то когда разворачиваю панельку, то часть текста пропадает. Так же почему-то в журнале заданий идёт дополнительная пометка "трофейных"
![str](https://user-images.githubusercontent.com/23438485/28956828-ad19ea40-78f7-11e7-9d94-8ee2c935a5c9.png)
2. Хотел бы спросить, может ли русификатор вызывать вылеты? Пока не удалось выявить конкретную последовательность, но уже несколько раз игра выдавала excepcion, когда на actionbar'е висит (и выбрана) например базука, а в инвентаре берёшь пкм-мом другую.

**Comment by UniverseGuard** [comment]
Это не дополнительная пометка. Сам предмет называется Трофейный ..... 

А подобных вылетов никогда не было :/ Может дело не в русификаторе?

**Comment by MonsterNya** [comment]
Ну ладно, это уже тонкости, хотя мешать название предмета с его категорией такое себе...
По поводу вылетов, кроме руса других модов у меня не стоит.

В русификаторе просочилась какая-то стрелка, которая растягивает окно (сравнивать с первым скриншотом выше)
![str](https://user-images.githubusercontent.com/23438485/28959021-5bbd1c9e-7901-11e7-856e-9270687bb16d.png)

**Comment by Xorras** [comment]
Ну квест сейчас поправлю, а насчет растягивания... Ну пришлось растянуть это окно. Некоторые цели заданий просто не влазят в не расширенную версию. Посмотрим если можно вернуть.

**Comment by MonsterNya** [comment]
очепятка (блин скрин криво вышел, но суть видно)
![str](https://user-images.githubusercontent.com/23438485/28965245-c5713910-7918-11e7-863c-894050a56a0f.png)

**Comment by MonsterNya** [comment]
![str](https://user-images.githubusercontent.com/23438485/28965337-3af828ba-7919-11e7-9f97-dfc419f72e8e.png)

**Comment by MonsterNya** [comment]
![str](https://user-images.githubusercontent.com/23438485/28965433-b299a42a-7919-11e7-85d8-a334cf79c011.png)

**Comment by Xorras** [comment]
А скриншоты случайно взяты не до последнего патча? Потому что я определенно помню что менял "and" на "и"

**Comment by MonsterNya** [comment]
Качал с гитхаба "Очередной недо-релиз #34", правда в игре на нонстим версии имеет такое вот описание
![str1](https://user-images.githubusercontent.com/23438485/28965834-c2a95746-791b-11e7-9660-58144b40144c.png)

**Comment by MonsterNya** [comment]
фраза проходящего жителя
![str](https://user-images.githubusercontent.com/23438485/28965852-e1c50fbc-791b-11e7-8a32-2cf74ec4c68b.png)

**Comment by Xorras** [comment]
Кстати, спасибо и тебе за репорты. Такие люди как вы просто сокровище.))

**Comment by MonsterNya** [comment]
странное название, хотя вроде в самом квесте написано
![str](https://user-images.githubusercontent.com/23438485/28966483-2198d166-791f-11e7-8be3-118399463fe5.png)

**Comment by MonsterNya** [comment]
Рад помочь =)

**Comment by MonsterNya** [comment]
![str](https://user-images.githubusercontent.com/23438485/28966772-ac52b9b0-7920-11e7-8b75-446381ae0e13.png)

**Comment by MonsterNya** [comment]
![str](https://user-images.githubusercontent.com/23438485/28966820-ea861056-7920-11e7-84f7-4c87808002c3.png)

**Comment by MonsterNya** [comment]
первое слово можно убрать, чтобы влезло. то что она декоративная и так понятно, ибо в описании нету характеристик. 
![str](https://user-images.githubusercontent.com/23438485/28966939-7fc9a8f8-7921-11e7-83b8-d7e02d778aa4.png)

**Comment by MonsterNya** [comment]
не русовед, но вроде раздельно
![str](https://user-images.githubusercontent.com/23438485/28967498-0da06f02-7924-11e7-9b94-0975c7dbfa27.png)

**Comment by MonsterNya** [comment]
проблемы переноса
![str](https://user-images.githubusercontent.com/23438485/28967725-29ee010a-7925-11e7-9228-716e4e282596.png)

**Comment by MonsterNya** [comment]
1. пробел
2. может можно сделать перенос?
![str](https://user-images.githubusercontent.com/23438485/28967987-847c03a0-7926-11e7-9c99-b7083a1ea3eb.png)

**Comment by UniverseGuard** [comment]
Все правильно написано. На крайний случай, загугли.

**Comment by MonsterNya** [comment]
Мне тоже показалось слитно, но гугл выдал только раздельные результаты.

**Comment by Xorras** [comment]
Guard, не влетай с ноги, ошибки были и уже исправлены.)

**Comment by MonsterNya** [comment]
может специально, но пока замечал только лишние "с"
![str](https://user-images.githubusercontent.com/23438485/28968256-d1e388b0-7927-11e7-8711-a868b5f85f66.png)

**Comment by MonsterNya** [comment]
не знаю, можно ли тут что-то сделать, но для отчётности
![str](https://user-images.githubusercontent.com/23438485/28968382-5ddf266c-7928-11e7-959d-d161029eb08e.png)

**Comment by UniverseGuard** [comment]
Говорить можно ПРО   ЗАПАС. Но запас на будущее - ПРОЗАПАС. Существительное, пишется слитно.

**Comment by MonsterNya** [comment]
Хорошо-хорошо, вам виднее)
________________________________________
![str](https://user-images.githubusercontent.com/23438485/28968592-5be04e26-7929-11e7-93d7-554db42d05a9.png)

**Comment by UniverseGuard** [comment]
Да дело не в этом. Не хочу, чтобы что-либо правильное исправляли на неправильное. Особенно с орфографией и пунктуацией.

**Comment by MonsterNya** [comment]
![str](https://user-images.githubusercontent.com/23438485/28968654-c3b99a70-7929-11e7-8e70-5af5e4ae6c7e.png)

**Comment by MonsterNya** [comment]
Ну я сразу написал, что не уверен. А так в подобное я обычно не лезу.

**Comment by Xorras** [comment]
Товарищ монстер, а вы можете заскринить если где в квестах попадётся "главаря своей банды"? Так как это часть генератора предложений, менять на именительный падеж может быть... проблематичным.

**Comment by MonsterNya** [comment]
Постараюсь, если увижу.
________
Тут я так понимаю ничего нельзя сделать с окончанием, т.к. оно берется из текста квеста?
![str](https://user-images.githubusercontent.com/23438485/28969076-b2be0984-792b-11e7-8d19-95c1bf012139.png)

**Comment by Xorras** [comment]
Сделать то что-то можно... Ладно, попробуем изменить ~~эту дичь~~ это дело

**Comment by MonsterNya** [comment]
Предложу замену - Превращает в сферу, для прохождения труднодоступных мест! [F]
По моим подсчётам влезет
![str](https://user-images.githubusercontent.com/23438485/28969692-4d65a544-792e-11e7-9756-cf02b18a009e.png)

**Comment by MonsterNya** [comment]
По аналогии - Превращает в сферу, которая может карабкаться по стенам! [F]
![str](https://user-images.githubusercontent.com/23438485/28969890-138845ce-792f-11e7-85f4-923941c8858a.png)

**Comment by MonsterNya** [comment]
Лишний пробел ^___^
![str](https://user-images.githubusercontent.com/23438485/28970650-fd2f1f3e-7931-11e7-8418-37c6a308a794.png)

**Comment by Xorras** [comment]
Он не лишний, в оригинале тоже стоят в этих местах. Зачем стоят — неизвестно. ¯\\\_(ツ)_/¯

**Comment by MonsterNya** [comment]
я же специально проверил заранее)
но да, получается там нужен еще один, а не лишний
![str](https://user-images.githubusercontent.com/23438485/28970905-d212a072-7932-11e7-88ac-7420f68de178.png)

**Comment by Xorras** [comment]
Ну я же говорю что были, просто мы из названия убрали.

**Comment by Xorras** [comment]
Так как у меня нет эстетического вкуса то спрошу тебя (вас, если кто-еще заглянет) насчет фотки цели
![https://image.prntscr.com/image/xzmi7RrvS3izNqfrgMvI3w.png](https://image.prntscr.com/image/xzmi7RrvS3izNqfrgMvI3w.png)
Так нормально выглядит? (падежи не менял, просто квест в логе нашелся)

**Comment by MonsterNya** [comment]
Немного не влазит и написано странно, предложу замены:
Семена травы с цветами
Семена травы с цветками
Семена цветочной травы
![starbound 08 04 2017 - 18 05 55 02](https://user-images.githubusercontent.com/23438485/28974686-cf6c3696-793f-11e7-87c8-912baab039ba.png)

**Comment by MonsterNya** [comment]
**Xorras**
Как по мне - всё ок.

**Comment by MonsterNya** [comment]
что-то не сходится
![starbound 08 04 2017 - 19 52 26 04](https://user-images.githubusercontent.com/23438485/28984721-027e5e7e-7968-11e7-9b95-aa8992c716f2.png)

**Comment by MonsterNya** [comment]
![starbound 08 04 2017 - 21 25 50 06](https://user-images.githubusercontent.com/23438485/28984813-5f2bd4f8-7968-11e7-9006-acd3705708ff.png)

**Comment by MonsterNya** [comment]
1. если убрать слово "меха", то должно влезть + совпадать
2. вопрос стандартизации названий
![starbound 08 04 2017 - 21 07 52 05](https://user-images.githubusercontent.com/23438485/28985269-67b18436-796a-11e7-8b4e-48dcdc1c45e9.png)

**Comment by MonsterNya** [comment]
немного не влазит, но тут наверное вариант только если сократить до
В здоровом теле - здор. дух
![starbound 08 04 2017 - 23 13 36 08](https://user-images.githubusercontent.com/23438485/28985314-9fc6a1f8-796a-11e7-9627-baa99284e62c.png)

**Comment by Xorras** [comment]
Всё там сходится, считай что имя этого черного рыцаря... то которое написано в квесте.:D

**Comment by MonsterNya** [comment]
Ради бога НЕ ПИНАЙТЕ, но мне КАЖЕТСЯ, там должно быть "в свете" или "на свету".
![starbound 08 06 2017 - 22 38 46 02](https://user-images.githubusercontent.com/23438485/29016482-4f782828-7b5b-11e7-86da-c34deb4ba7d7.png)

**Comment by MonsterNya** [comment]
остатки старого КЭП
![starbound 08 07 2017 - 09 49 26 01](https://user-images.githubusercontent.com/23438485/29016553-86bea7bc-7b5b-11e7-8578-36f5da62b5f0.png)

**Comment by MonsterNya** [comment]
Может просто еще не перевели, а может и забыли
![starbound 08 07 2017 - 09 58 03 05](https://user-images.githubusercontent.com/23438485/29016599-b6d4431c-7b5b-11e7-8c3d-df2809083b8f.png)

**Comment by Xorras** [comment]
>Ради бога НЕ ПИНАЙТЕ, но мне КАЖЕТСЯ, там должно быть "в свете" или "на свету".

*заносит ногу для пинка*
Там вообще отсылка к Толкину оказывается в оригинале. По крайней мере так одно стихотворение начинается с этой фразы (английской).

**Comment by MonsterNya** [comment]
ууу, посыпаю голову пеплом)

**Comment by MonsterNya** [comment]
пробудилАсь?.. или опять отсылка ( ╯°□°)╯┻┻
![str](https://user-images.githubusercontent.com/23438485/29046303-8c3c1cd2-7bcf-11e7-8688-8bffb3d7ff49.png)

**Comment by Xorras** [comment]
Не-не-не, я про отсылку в оригинале тогда говорил, ошибка была и фраза заменена на более подходящую. 
Кстати в последнем скриншоте "спокойстве" почему не подчеркнуто?))

**Comment by MonsterNya** [comment]
Хе-хе, перечитывал раза 2-3 и всё равно не заметил, надо на свежую голову анализировать)

**Comment by MonsterNya** [comment]
по поводу более старого скрина 
![starbound 08 04 2017 - 19 52 26 04](https://user-images.githubusercontent.com/23438485/28984721-027e5e7e-7968-11e7-9b95-aa8992c716f2.png)
и вот при сдаче квеста
![starbound 08 08 2017 - 08 49 58 06](https://user-images.githubusercontent.com/23438485/29058866-5e2bc38c-7c1b-11e7-8b60-ff064989f158.png)

**Comment by MonsterNya** [comment]
1. Разных фраз при смене пола (к которому обращаются) я думаю тут нет, так что предложу нейтральный вариант
Я хочу, чтобы у Ксоч просто челюсть упала/выпала!
2. Подразумевает то, что нужно создать, а не объединить. Предложу:
объединения в
соединения вместе в
3. Опять же пол (говорящего), предложу нейтрально:
Мне можно было сделать это и самостоятельно, но я ничего в этом не смыслю.
Это можно было сделать и мне, но я ничего в этом не смыслю.
4. на себЯ. и вконце по идее должен быть знак "?".
p.s. возможно перед "соединения" двойной пробел
![starbound 08 08 2017 - 08 47 31 05](https://user-images.githubusercontent.com/23438485/29060090-f7063e5c-7c20-11e7-9a40-d477ee9e3510.png)

**Comment by MonsterNya** [comment]
1. мне кажется там двойной пробел
2. нужен пробел
![starbound 08 08 2017 - 09 15 26 07](https://user-images.githubusercontent.com/23438485/29060234-94d75396-7c21-11e7-8e86-f1b492bbace9.png)

**Comment by MonsterNya** [comment]
![starbound 08 08 2017 - 08 46 04 04](https://user-images.githubusercontent.com/23438485/29060298-d8279a7a-7c21-11e7-84d5-01985210d3a6.png)

**Comment by MonsterNya** [comment]
опять не знаю, упущение или просто не перевели
![starbound 08 08 2017 - 08 44 08 03](https://user-images.githubusercontent.com/23438485/29060334-04d4068a-7c22-11e7-9f2a-47a710d7534f.png)

**Comment by MonsterNya** [comment]
один и тот же косяк с "на западе" или это всё разное?
![starbound 08 08 2017 - 08 16 36 01](https://user-images.githubusercontent.com/23438485/29060507-c1a8b8aa-7c22-11e7-863e-5d33e7605efa.png)

**Comment by Xorras** [comment]
Просто из вредности, я закрою тему, потому что скроллить уже далековато(да и чтоб не путаться что исправлено). Пересоздай, когда найдешь ещё.:p

**Comment by xomachine** [comment]
В идеале вообще на одну пачку багов - одну тему. Исправил - закрыл. Тут ограничений на количество тем нет
