### ISSUE TITLE
Чем мы руководствовались?

### ISSUE THREAD

**Issue by UniverseGuard** [SBT-community/Starbound_RU#63]
![20170814110753_1](https://user-images.githubusercontent.com/30653739/29263350-0c5e546e-80e1-11e7-99df-5bb0c07df4d8.jpg)
![20170814110734_1](https://user-images.githubusercontent.com/30653739/29263351-0c7843a6-80e1-11e7-864a-e5f8237662d0.jpg)
![20170814110740_1](https://user-images.githubusercontent.com/30653739/29263352-0c87a33c-80e1-11e7-84a2-1dba918c3969.jpg)
Эт" , эт"т?

**Comment by xomachine** [comment]
Это остатки с тех далёких времён, когда переводили все кому не лень без какого-либо контроля. Сейчас поправлю.

**Comment by UniverseGuard** [comment]
@xomachine Тему закрыть?

**Comment by xomachine** [comment]
Всё починил.
