### ISSUE TITLE
Ну не нормально эт" всё. Руки оторвать тем, кто переводил хилотлов

### ISSUE THREAD

**Issue by UniverseGuard** [SBT-community/Starbound_RU#64]
![20170814233004_1](https://user-images.githubusercontent.com/30653739/29315042-ac4b62e4-81c9-11e7-9617-1f72f57891f4.jpg)
![20170814233009_1](https://user-images.githubusercontent.com/30653739/29315045-b16129e4-81c9-11e7-85ad-bb1efa33b199.jpg)
![20170814233015_1](https://user-images.githubusercontent.com/30653739/29315048-b549e0fa-81c9-11e7-95ff-39f71705fc80.jpg)

Эт" вопрос?
В любом случае нибудь через дефис
![20170814234426_1](https://user-images.githubusercontent.com/30653739/29315067-d037170c-81c9-11e7-8d2c-c4ee1a244192.jpg)

Либо оно не дописано, либо кто-то точку забыл.
![20170814234528_1](https://user-images.githubusercontent.com/30653739/29315077-e0667bcc-81c9-11e7-9f5e-67e257509143.jpg)

**Comment by Xorras** [comment]
Насчет Эт"

Видимо кто-то пытался сохранить оригинальную конструкцию писания фраз новакидов:

Ориг - A big ol' dumpster.
Кто-то перевел - Эт' cтарая большая мусорка.

**Comment by UniverseGuard** [comment]
Да мне вообщем-то всё равно, просто надо перефиксить всё это

**Comment by UniverseGuard** [comment]
Точека.
![20170814235141_1](https://user-images.githubusercontent.com/30653739/29331225-6291775c-8204-11e7-99c6-d3acc0823b11.jpg)

Запяте
![20170815150443_1](https://user-images.githubusercontent.com/30653739/29331241-6eb89eac-8204-11e7-9fd8-d545eaee5894.jpg)

2 запяте

![20170815150446_1](https://user-images.githubusercontent.com/30653739/29331276-8bd0dfd6-8204-11e7-9c19-b8fa71a1f88a.jpg)

Точека
![20170815150500_1](https://user-images.githubusercontent.com/30653739/29331299-960174ca-8204-11e7-84ec-b7f4d0d0eed8.jpg)

**Comment by UniverseGuard** [comment]
Я тут задумался, а ведь делать флоранам "тьссся" / "тссся" - вообще неправильно :/ Тся, ться произносятся как [ца]... Ну это так.

**Comment by UniverseGuard** [comment]
@Xorras Можно просто доступ к прямому редактированию? Я уже столько эт'х "эт'  ", " что"б " нашёл, что счёт потерял. Заодно везде "е" на "ё" заменю (где надо естественно).

**Comment by UniverseGuard** [comment]
![20170817153900_1](https://user-images.githubusercontent.com/30653739/29415543-0ddf48f6-836c-11e7-8e39-e7bde7be6ef9.jpg)
![20170817154049_1](https://user-images.githubusercontent.com/30653739/29415542-0ddc9b38-836c-11e7-94c6-5c67eede1e8b.jpg)

**Comment by UniverseGuard** [comment]
![20170817154429_1](https://user-images.githubusercontent.com/30653739/29415567-209bac96-836c-11e7-980d-75ba2824c7e6.jpg)

**Comment by UniverseGuard** [comment]
Задумчиво* 
![20170817122503_1](https://user-images.githubusercontent.com/30653739/29417371-ac356f4e-8371-11e7-9316-02c366894e41.jpg)

**Comment by Xorras** [comment]
Так, думаю, что всё исправил указанное здесь...

Дать то доступ можно, но тогда исправляй и другие ошибки которые найдешь. Ну например, ты пошел заменить е на ё, но в том же файле, в другом предложении ошибка. 
Как в последнем скриншоте например. Кроме задумчивый там должно быть "у меня есть так много" вместо "у меня есть там".  Пример конечно неудачный, но суть ты уловил думаю.

**Comment by UniverseGuard** [comment]
@Xorras no problems, partner.

**Comment by UniverseGuard** [comment]
Потом в новую тему лучше пачку закину.
