### ISSUE TITLE
Немного репорта

### ISSUE THREAD

**Issue by MonsterNya** [SBT-community/Starbound_RU#66]
![starbound 08 13 2017 - 20 38 49 01](https://user-images.githubusercontent.com/23438485/29448786-f4191ea2-8400-11e7-907d-ae0027800e4e.png)

**Comment by MonsterNya** [comment]
![starbound 08 13 2017 - 22 29 38 10](https://user-images.githubusercontent.com/23438485/29448806-06f1795c-8401-11e7-9e62-f7ef20cd4ef2.png)

**Comment by MonsterNya** [comment]
![starbound 08 13 2017 - 22 46 19 14](https://user-images.githubusercontent.com/23438485/29448832-1b173bc4-8401-11e7-8227-5afd2fd86ad6.png)

**Comment by xomachine** [comment]
Два последних переделаны полностью в рамках улучшения согласованности падежей в квестах

**Comment by MonsterNya** [comment]
Последняя версия рус-а от 18.08.2017
![starbound 08 21 2017 - 22 13 57 06](https://user-images.githubusercontent.com/23438485/29555264-c32aa84c-872a-11e7-98a8-ff9644fe3690.png)

**Comment by xomachine** [comment]
Кажется, остальное уже исправлено. Закрываю эту тему. Если ещё найдутся ошибки, создайте новую.
