### ISSUE TITLE
Данные доп. урона и крита у оружия

### ISSUE THREAD

**Issue by source-com** [SBT-community/Starbound_RU#79]
Последний и предпоследний релизы
Затерялась информация о дополнительных значениях урона и шанса крит. удара
![crit dmg](https://user-images.githubusercontent.com/27564550/34959548-6b397ce6-fa50-11e7-90e9-27c5483018ce.jpg)
![no crit no dmg](https://user-images.githubusercontent.com/27564550/34959549-6b590d5e-fa50-11e7-975e-46a19e59eeb9.jpg)

**Comment by Xorras** [comment]
Это не к нам. В ванильной игре таких значений нет
