### ISSUE TITLE
export_mod.py не экспортировать /glitchDescription

### ISSUE THREAD

**Issue by Pwrest** [SBT-community/Starbound_RU#85]
export_mod не экспортирует glitchDescription

`переведенный alpacacomponentrune.object.json`

> {
> 
>     "DeniedAlternatives": [],
>     "Files": {
>       "objects/alpaca/alpacacomponentrune/alpacacomponentrune.object": [
>         "/glitchDescription/glitchEmotedText"
>       ]
>     },
>     "Texts": {
>       "Eng": "A rune that signifies the most basic element of organic life.",
>       "Rus": "Руна символизирует базовую частицу органической жизни."
>     }

`экспортируется с export_mod.py alpacacomponentrune.object.patch`

> {
>     "op": "replace",
>     "value": "Древняя руна, символизирующая основную составляющую жизни.",
>     "path": "/description"
>   },
>   {
>     "op": "replace",
>     "value": "Старая руна, обозначает частицу жизни.",
>     "path": "/novakidDescription"
>   },
>   {
>     "op": "replace",
>     "value": "Ссстарые руны... эта означает частичку жжизни.",
>     "path": "/floranDescription"
>   },
>   {
>     "op": "replace",
>     "value": "Руна частицы жизни",
>     "path": "/shortdescription"
>   },
>   {
>     "op": "replace",
>     "value": "Это точно не руна Авиан, слишком технологично.",
>     "path": "/avianDescription"
>   },
>   {
>     "op": "replace",
>     "value": "Слишком продвинутый символ для такой старой руны. Выглядит как атом.",
>     "path": "/humanDescription"
>   },
>   {
>     "op": "replace",
>     "value": "Эта руна явно древняя, но демонстрирует высокий уровень научных знаний.",
>     "path": "/apexDescription"
>   },
>   {
>     "op": "replace",
>     "value": "Была ли эта руна создана расой, жившей среди звезд ещё до Хилотлов?",
>     "path": "/hylotlDescription"
>   }

glitchdescription отсутствует во всех файлах

**Comment by xomachine** [comment]
Не могу воспроизвести проблему. У меня эти описания создаются. 

![18-03-27_21 54 42](https://user-images.githubusercontent.com/3051015/37988757-5febbe84-320a-11e8-93b6-86f969155d2a.png)
