### ISSUE TITLE
1.4.0

### ISSUE THREAD

**Issue by DmitryRendov** [SBT-community/Starbound_RU#96]
Было бы замечательно возобновить работу ибо [вышла 1.4.0](https://starbounder.org/Version_1.4.0)

**Comment by DmitryRendov** [comment]
Добрейшего @xomachine, можно попросить залить новые тексты 1.4.0 для переводов, я бы смог заняться на досуге.

**Comment by xomachine** [comment]
База обновлена. Новый мод совместим с 1.4.0, по крайней мере на столько, на сколько мне удалось проверить.

**Comment by DmitryRendov** [comment]
Спасибо @xomachine. Eсли будет возможность - опубликуй альфа-бета релиз, ибо не все умеют собирать пакеты из исходников))

Плюс ко всему старая версия мода 1.3.4 ломает новые квесты Peacekeepers - заодно проверим что новая этой проблемы лишена.
